### ISSUE TITLE
One to Many objects updated but changes not reflected in the response when using prefetch_related

### ISSUE THREAD

**Issue by sikko** [tomchristie/django-rest-framework#4551] opened 2016-10-10 18:59 UTC
For the sake of simplicity, I'll be talking about Posts and Comments event though my models are different ones. This could be a duplicate of https://github.com/tomchristie/django-rest-framework/issues/1556, but it's closed and is about an outdated version of DRF.

## Steps to reproduce

I created a PostViewSet and redefined the get_queryset method.

```
def get_queryset(self):
    queryset = Post.objects.prefetch_related('comments')
    return queryset
```

I'm trying to update the full Post object. For this I send a PUT request containing the post with its comments. I had to redefine the update method in the serializer to handle nested comments.

## Expected behavior

The new comments are added to the post, the updated post is served back in the http response. With all updated fields, and updated comments.

## Actual behavior

The new comments are indeed added to the post, but the returned item in the http response is the one BEFORE it was updated. Removing the prefetch_related solves the issue but I need it.

**Comment by xordoquy** [comment] 2016-10-10 19:25
It's rather a duplicate of #2442.
Using prefetch requires the developer to override the returned value.

**Closed by xordoquy** 2016-10-10 19:25 UTC

**Comment by tomchristie** [comment] 2016-10-10 19:41
Bumped the priority of #2442
