### ISSUE TITLE
DecimalField fails when `max_digits=None`

### ISSUE THREAD

**Issue by terramars** [tomchristie/django-rest-framework#4372] opened 2016-08-09 22:12 UTC
## Steps to reproduce

1) Create a DecimalField inside a serializer with max_value, min_value, and decimal_places set, but set max_digits = None.  EG: serializers.DecimalField(max_value=100, min_value=0, decimal_places=10, max_digits=None)
2) call serializer.is_valid()
3) observe traceback similar to the following : 

Traceback (most recent call last):
  File "~/api/views.py", line 263, in monitor
    serializer.is_valid()
  File "~/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 213, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "~/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 407, in run_validation
    value = self.to_internal_value(data)
  File "~/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 437, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "~/env/local/lib/python2.7/site-packages/rest_framework/fields.py", line 488, in run_validation
    value = self.to_internal_value(data)
  File "~/env/local/lib/python2.7/site-packages/rest_framework/fields.py", line 959, in to_internal_value
    return self.quantize(self.validate_precision(value))
  File "~/env/local/lib/python2.7/site-packages/rest_framework/fields.py", line 1022, in quantize
    context=context
  File "/usr/lib/python2.7/decimal.py", line 2455, in quantize
    if not (context.Etiny() <= exp._exp <= context.Emax):
  File "/usr/lib/python2.7/decimal.py", line 3898, in Etiny
    return int(self.Emin - self.prec + 1)
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

## Expected behavior

is_valid returns true if the value is between min and max, without concerning itself with the number of digits / precision of the number, OR do not accept None as a valid value for max_digits.

## Actual behavior

an exception is raised, which is difficult to track down and counter intuitive.

**Comment by xordoquy** [comment] 2016-08-10 06:53
> is_valid returns true if the value is between min and max, without concerning itself with the number of digits / precision of the number, OR do not accept None as a valid value for max_digits.

Nop. `max_digits` is a required argument. It shouldn't be `None` or ignored. I'd assume you'll get a faster traceback if you simply ignore it.

What I'd be willing to do here would be:
- to add an explicit mention in the doc about the required fields.
- to add an assert about `max_digits` not being None.

Closing this issue meanwhile as we're not making `max_digit` optional.

**Comment by terramars** [comment] 2016-08-10 06:56
That makes sense, yeah assert when max_digits is None would be great.
Definitely easier for people to debug.

**Comment by tomchristie** [comment] 2016-08-10 13:17
Taking a look through the code it's not clear if `max_digits` is intended to be optional or not. We *do* switch on `if self.max_digits is None`, and a `DecimalField` *without* digit restrictions is a reasonable enough use case. Worth putting on to the queue to have a second think over.

**Comment by xordoquy** [comment] 2016-08-10 13:23
@tomchristie `max_digits` is not a keyword argument in `__init__` therefore it's supposed to be required. Same applies to `decimal_field`. This is likely inherited from Django's own `DecimalField`.
If it becomes an optional argument, we'll need to cover the case where it's over the Django's Model boundaries.

**Comment by tomchristie** [comment] 2016-08-10 13:27
Passing the argument is required, but it may be None. `None` will have worked up until #4339, so figure it's worth resolving.

**Comment by xordoquy** [comment] 2016-08-10 13:31
I don't think it'll worked before as there are other calls to quantize anyway.

**Closed** 2016-08-10 13:39 UTC
Labels: Needs design decision

**Comment by tomchristie** [comment] 2016-08-10 13:40
Comes across as a regression to me, tho yes slightly borderline behavior, but not massivly. Test looks happy now.

**Comment by bravmi** [comment] 2020-12-24 09:18
From my tests and the source, it seems `decimal_places` is also allowed to be None but it is not mentioned in the docs.  

Also, it'd be cool if the docs state exactly what happens when either of them is None.
