### ISSUE TITLE
ModelSerializer update, race conditions with calls to PATCH can cause boolean fields with defaults to be updated erroneously.

### ISSUE THREAD

**Issue by Jafula** [tomchristie/django-rest-framework#2621] opened 2015-03-01 10:18 UTC
I don't have time to reproduce but I think worth letting you know. I think I have patch calls that end up racing each other to update the same instance with different fields and values. In my case, I have boolean fields with default=False and under Django 1.6.10 (Python 3.4) with the DRF 3.0.5 they were sometimes getting set to their default rather than the value they were set by another process moments ago.

I'm assume some sort of race condition as my functional tests fail every other time and it can any number of the three boolean fields that gets set incorrectly even though it appeared everything worked correctly.

In my case, I am overriding update so can change instance.save to specify updating only the fields that were changed (see below). 

    class ModelSerializer(Serializer):
        def update(self, instance, validated_data):
            raise_errors_on_nested_writes('update', self, validated_data)

            for attr, value in validated_data.items():
                setattr(instance, attr, value)
            instance.save(update_fields=validated_data.keys())

            return instance

Is it worth doing the same in DRF proper as it may save someone from some subtle issues? The change shouldn't cause an problems.

**Comment by Jafula** [comment] 2015-03-01 10:29
Hmmm, update_fields is new in Django 1.5, that is not going to work with 1.4 which you are still supporting. Oh well, perhaps a note in the documentation? Happy for this to be closed if you deem it not a problem.

**Comment by tomchristie** [comment] 2015-03-02 08:09
Hiya! Thanks for the info on this. Going to close it at the moment due to lack of reproducibility, but happy to re-assess if anyone is able to present a more actionable example. The `update_fields` could be a reasonable thing to do, but I suspect we'd introduce more issues than we'd resolve. And yes, highly concurrent applications *may* need to take a look at properly wrapping their view logic in transactions, which we don't currently handle by default.

**Closed by tomchristie** 2015-03-02 08:09 UTC

**Comment by askholme** [comment] 2015-03-02 09:15
As pointed out by in #2622 this can likely be mitigated by using the [PartialUpdateSerializerMixin](http://chibisov.github.io/drf-extensions/docs/#partialupdateserializermixin) from drf-extensions

**Comment by Jafula** [comment] 2015-03-02 09:18
The drf-extensions look good. Thanks for the tip.
