### ISSUE TITLE
Version 3.3 broke our file uploads

### ISSUE THREAD

**Issue by henkvos** [tomchristie/django-rest-framework#3591] opened 2015-11-04 13:02 UTC
request.data dict does not contain the uploaded file when using FileUploadParser in v3.3. for now reverting to 3.2.4 solves this issue. I could not find in the docs that something has changed or did i read over it?

**Comment by xordoquy** [comment] 2015-11-04 13:03
Duplicate of #3578.

**Closed by xordoquy** 2015-11-04 13:03 UTC
