### ISSUE TITLE
Make it possible to define separate methods for GET and POST in viewsets

### ISSUE THREAD

**Issue by MadWombat** [tomchristie/django-rest-framework#3822] opened 2016-01-11 18:36 UTC
It seems awkward to do
```
if request.method == "GET":
    ... do something ...
elif request.method == "POST":
   ... do something else ...
```

Is there a way to separate method handling in a viewset. Something like
```
class MyModelViewSet(viewsets.GenericViewSet):
    model = MyModel

    @detail_route(methods=["GET"], url_path="/path")
    def get_stuff(self, request, pk=None):
        ... do stuff...

    @detail_route(methods=["POST"], url_path="/path")
    def post_stuff(self, request, pk=None):
        ... do other stuff ...
```

**Comment by kevin-brown** [comment] 2016-01-11 18:49
This is pretty much a duplicate of https://github.com/tomchristie/django-rest-framework/issues/2708, which has a few linked PRs/tickets which explain the decisions that have been made.

You could redesign your view to make trigger call `post/get_stuff` or write your own decorator to support multiple routes for a single url. You could make it a 3rd party and add it to [the documentation](http://www.django-rest-framework.org/topics/third-party-resources/#how-to-create-a-third-party-package).

**Closed by kevin-brown** 2016-01-11 18:49 UTC

**Comment by MadWombat** [comment] 2016-01-11 21:46
So there are now 5 tickets requesting a change of a few lines. Oh well.
