### ISSUE TITLE
Wrong placeholder in german l10n string (v3.1.0)

### ISSUE THREAD

**Issue by mkemmerling** [tomchristie/django-rest-framework#2653] opened 2015-03-07 15:31 UTC
There is a wrong placeholder in _locale/de/LC_MESSAGES/django.po_, line 150:

<pre>
#: fields.py:659 fields.py:693 fields.py:726
msgid "Ensure this value is greater than or equal to {min_value}."
msgstr "Stelle sicher, dass dieser Wert größer oder gleich {max_value} ist."
</pre>

The translation string should clearly include _min_value_ instead of _max_value_.

**Comment by jpadilla** [comment] 2015-03-07 15:32
Duplicate of https://github.com/tomchristie/django-rest-framework/issues/2645

**Closed by jpadilla** 2015-03-07 15:32 UTC

**Comment by mkemmerling** [comment] 2015-03-07 15:34
Oops,I  just wanted to close the issue myself. Sorry for not checking before committing.
