### ISSUE TITLE
Can't add documentation specifically for extra action routes

### ISSUE THREAD

**Issue by blag** [tomchristie/django-rest-framework#4818] opened 2017-01-15 00:25 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a `ViewSet` with an [extra action](http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing), include a docstring on the ViewSet:

   ```python
   class ThingViewSet(viewsets.ModelViewSet):
       """
       ViewSet docstring
       """"
       
       queryset = Thing.objects.all()
       serializer_class = ThingSerializer
   ```

2. Add a `detail_route` with `get` in the allowed methods

   ```python
       @detail_route(methods=['get'])
       def specific_action(self, request, pk=None):
           """
           detail_route docstring
           """
           pass
   ```

3. Register the ViewSet as usual

## Expected behavior

The documentation of the ViewSet listing itself is `ViewSet docstring`.

The `specific_action` documentation should be `detail_route docstring`.

## Actual behavior

The documentation of the ViewSet listing itself is `ViewSet docstring` (expected).

The `specific_action` documentation **is also** `ViewSet docstring` (**NOT** expected).

-------------------

Since extra action routes may break RESTfulness more than normal ViewSets, they are more likely to need more specific documentation than the ViewSet itself.

It also greatly overcomplicates the ViewSet documentation to include documentation about the specific extra action routes.

All of this means that the extra action routes usually need different documentation than the usual ViewSet endpoints.

**Comment by tomchristie** [comment] 2017-01-18 12:22
Worth us making sure this gets properly reviewed for 3.6 since API docs will be one of our headline features there.

**Comment by rpkilby** [comment] 2017-01-18 12:27
Duplicate of #3271?

**Comment by tomchristie** [comment] 2017-01-18 12:37
Partly, yes!

**Comment by blag** [comment] 2017-01-18 16:21
I didn't see #3271 when I submitted this - yes, it's a duplicate of that. Since that's also been tagged for 3.6.0 I'd be fine with closing this.

**Closed** 2017-01-18 16:35 UTC
Labels: Needs further review
