### ISSUE TITLE
Issue with *list_route* decorator

### ISSUE THREAD

**Issue by Heroico** [tomchristie/django-rest-framework#3599] opened 2015-11-04 22:07 UTC
Hi there!

I have added an HTTP method to a view set, with the **SimpleRouter** and the **list_route** decorator.
I am having an issue with the permission classes for this method alone. I set a permission (different from the ViewSet) in the decorator as in the current docs:

```python
#/jobs/
class JobViewSet(ModelViewSet):
    serializer_class = JobSerializer
    permission_classes = (AuthenticatedOwnerPermission, )
...
    #/jobs/active
    @list_route(methods=['get'], permission_classes=[AuthenticatedUserPermission])
    def active(self, request, *args, **kwargs):
        active = Job.active_job(self.request.user)
        data = self.get_serializer(active).data if active else None
        return Response(data)
```

But this different permission class is ignored. Maybe this is on purpose?
Or should it be working as it is, and the problem is elsewhere?

Thanks!

**Comment by tomchristie** [comment] 2015-11-04 22:21
Looks fine on first sight. Assume problem is elsewhere?... (Sorry brief, on phone)

**Comment by Heroico** [comment] 2015-11-05 13:09
Well, it beats me. My user case is pretty simple actually. I added some logging, and neither the ViewSet permission class nor the decorator one are being called.

Please let me know if there if there is any information I could provide to sort this out, or any suggestion. Thanks again!

**Comment by dursk** [comment] 2015-12-05 21:23
Just set this up from scratch and ran through it all locally: using the `@list_route` decorator on a `ViewSet` and specifying a `permission_classes` that is different than the one of the class. Everything checked out and seems to be working as expected, the permission class specified in the decorator is the one being called when hitting the endpoint for that view.

**Comment by tomchristie** [comment] 2015-12-07 09:44
Closing pending a reproducible example.

**Closed by tomchristie** 2015-12-07 09:44 UTC
Labels: Needs information

**Comment by narwhaljames** [comment] 2018-06-19 19:42
I was able to get this to occur. The problem seems to stem from the fact that the original permission_class on the class will 403 before the list_route permission_class is able to override it.
