### ISSUE TITLE
ListSerializer.to_representation cuts data and KeyError is raised if the queryset used has been modified

### ISSUE THREAD

**Issue by MattBlack85** [tomchristie/django-rest-framework#2727] opened 2015-03-19 22:44 UTC
I discovered this problem after upgrading to 3.1, after 86c5fa240131fe20121db707b0324a32967987ab if a QuerySet is passed as iterable `data.all()` will be called. That's fine until we start to add extra data to the QS and use normal serializers for output.
Case:
```
objs = Model.objects.filter(x=y)
for obj in objs:
    obj.update(extra_dict)
serializer = MySerializer(objs, many=True)
```
 `serializer.data` will contain only data from QS, ignoring totally the other portion of data added later and ending with a KeyError because we're missing fields that are declared on serializer, this wasn't happening before since `data.all()` wasn't called while passing QS around.

**Comment by xordoquy** [comment] 2015-03-19 22:48
It's the second time we are bitten by the QS reevaluation in the ListSerializer (previous was #2704).
I'm really not convinced 86c5fa240131fe20121db707b0324a32967987ab was a good idea after all.

**Comment by mcbhenwood** [comment] 2015-04-21 14:36
Seconded. This is currently causing some grief to me as well. @bakaat suggested this quick fix:

``Serializer(instance=list(objs), many=True)``

which "works" in terms of the data you get out, but isn't desirable for large querysets

**Comment by bakaat** [comment] 2015-04-21 14:59
Indeed it's not. And it would possibly require you to rewrite all calls to serializer.

While that's what I suggested, I actually worked around it by subclassing Serializer (We've got our own base class extending the ModelSerializer anyways)

```
from rest_framework import serializers

class ModelSerializer(serializers.ModelSerializer):
    def __new__(cls, *args, **kwargs):
        if 'many' in kwargs and isinstance(
                kwargs.get('instance', None), QuerySet):
            kwargs['instance'] = (x for x in kwargs['instance'])
        return super(ModelSerializer, cls).__new__(cls, *args, **kwargs)
```

Generator should be more efficient than list and still prevents reevalution. This said it still remains a `quick fix`

**Comment by tomchristie** [comment] 2015-06-24 09:21
> That's fine until we start to add extra data to the QS

@MattBlack85 (or anyone else)

On further review I  didn't fully understand this.
What exactly did you mean here - what kind of extra data, and added how? could you give an example?

**Comment by tomchristie** [comment] 2015-06-24 09:25
Closing as a duplicate of #2704, but it'd be useful to know if there are other types of "extra data" along with `prefetch_related` that also demonstrate the issue.

**Closed by tomchristie** 2015-06-24 09:25 UTC
Labels: Needs design decision

**Comment by bakaat** [comment] 2015-06-24 09:27
@tomchristie In my situation it was something like

```
qs = Abc.objects.all()[:10]
for o in qs:
    o.additional_attr = 'abc'
Serializer(instance=qs, many=True)
```

This actually causes the items in qs to be re-fetched from the db and `additional_attr` to be lost in the process (as far as I recall at this moment)

**Comment by tomchristie** [comment] 2015-06-24 09:29
Okay. That's a slightly quirky thing to do, but it is at least a very simple demonstration of the issue! :) Thank you.

**Comment by bakaat** [comment] 2015-06-24 09:43
Yup :)

**Comment by MattBlack85** [comment] 2015-06-24 10:19
My case regards fetching data from another service, having then those data in a dict I was trying to update every object in my QS with that dictionary I got from the service:
```Python
fetched_data = {'x': {'attr_a': 'some', ...},...}
qs = Model.objects.all().values()
for obj in qs:
    obj.update(fetched_data.get(obj['id']), {})
```
almost the same

**Comment by tomchristie** [comment] 2015-06-24 10:22
Grand, thanks both.
