### ISSUE TITLE
Inspecting relationships.

### ISSUE THREAD

**Issue by harisibrahimkv** [tomchristie/django-rest-framework#4155] opened 2016-06-01 07:28 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
>>> from stories.serializers import QuestiongroupSerializer
>>> serializer = QuestiongroupSerializer()
>>> print repr(serializer)
<stories.serializers.QuestiongroupSerializer object at 0x3165490>
```
## Expected behavior

From http://www.django-rest-framework.org/api-guide/relations/#inspecting-relationships

```
>>> from myapp.serializers import AccountSerializer
>>> serializer = AccountSerializer()
>>> print repr(serializer)  # Or `print(repr(serializer))` in Python 3.x.
AccountSerializer():
    id = IntegerField(label='ID', read_only=True)
    name = CharField(allow_blank=True, max_length=100, required=False)
    owner = PrimaryKeyRelatedField(queryset=User.objects.all())
```
## Actual behavior

As mentioned in the steps to reproduce.

**Comment by carltongibson** [comment] 2016-06-01 07:34
@harisibrahimkv Can you add the source for the `QuestiongroupSerializer` class please?

**Comment by xordoquy** [comment] 2016-06-01 08:30
@harisibrahimkv I'm closing this because there isn't enough information to make it actionable in its current form.
We'll reopen if you can make a test case that highlights the issue or a complete snippet because it's not reproducible in its current form:

    >>> from workshop_drf.todo.serializers import Owner
    >>> o = Owner()
    >>> print(o)
    Owner():
        username = CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, validators=[<django.core.validators.RegexValidator object>, <UniqueValidator(queryset=User.objects.all())>])
        email = EmailField(allow_blank=True, label='Email address', max_length=254, required=False)
    >>> print(repr(o))
    Owner():
        username = CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, validators=[<django.core.validators.RegexValidator object>, <UniqueValidator(queryset=User.objects.all())>])
        email = EmailField(allow_blank=True, label='Email address', max_length=254, required=False)
    >>>

**Closed by xordoquy** 2016-06-01 08:30 UTC

**Comment by harisibrahimkv** [comment] 2016-06-08 09:04
My bad. I was on a different virtual environment that had DRF 2.x. This means I did not test it with the latest stable release.

**Comment by xordoquy** [comment] 2016-06-08 09:16
No problem. Thanks for the feedback.
