### ISSUE TITLE
List of file fields:

### ISSUE THREAD

**Issue by tigrus** [tomchristie/django-rest-framework#4184] opened 2016-06-09 13:57 UTC
## Checklist

- [+] I have verified that that issue exists against the `master` branch of Django REST framework.
- [+] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [+] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [+] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [+] I have reduced the issue to the simplest possible case.
- [] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Define serializer as following: 
```
class FilesSerializer(serializers.ModelSerializer):
    files = serializers.ListField(
        child=serializers.FileField(),
    )
```

## Expected behavior

It should render list of file inputs in browserable API. Or at least it should render non-editable list of files. 
Model should stay editable via browserable API. 

## Actual behavior

It renders text input with value like `['/file/1', '/file/2']`. And when we press "PUT" button in browserable API - we get error `"The submitted data was not a file. Check the encoding type on the form."`

**Comment by tomchristie** [comment] 2016-06-09 14:52
Duplicate of #2483

**Closed by tomchristie** 2016-06-09 14:52 UTC

**Comment by tigrus** [comment] 2016-06-10 00:44
@tomchristie why you treat filefield as list? :) #2483 about nested lists.

**Comment by tomchristie** [comment] 2016-06-10 07:53
Retitled #2483 - wasn't well worded.

**Comment by tomchristie** [comment] 2016-06-10 07:55
For now you're going to need to treat this as a known constraint.
Forms don't easily support list inputs, so we need to emulate this, but it's a bunch of work to figure out, so don't expect it anytime soon.
I'd probably suggest treating file uploads as singular endpoints, as that'll give you more robust behavior in any case.
