### ISSUE TITLE
Nested writable ListFields break the browsable API

### ISSUE THREAD

**Issue by jackmccloy** [tomchristie/django-rest-framework#3500] opened 2015-10-14 21:29 UTC
When you do a PUT request via the browsable API on an endpoint that has a nested writable ListField in it's serializer, it wipes out any existing information in this list field. Since lists are not currently supported in HTML input, as the browsable API states, it seems to me that they should be ignored by the serializer's update method, as opposed to passing an empty list. This way a user could still use the browsable api to update the other non-ListFields without unexpectedly losing data. Thoughts?

Happy to work on a fix for this one over the weekend if it'd help. In the 3.0 release notes, it was mentioned that nested lists were planned for 3.1, and if/when nested lists are supported it'll render this issue moot.

**Comment by xordoquy** [comment] 2015-10-14 21:43
Duplicate of #2148

**Closed by xordoquy** 2015-10-14 21:43 UTC
