### ISSUE TITLE
PageNumberPagination returning same record for first 2 pages when page_size = 1

### ISSUE THREAD

**Issue by timothycoutlakis** [tomchristie/django-rest-framework#3270] opened 2015-08-13 23:59 UTC
As the title says.
When page_size = 1, I get the same record for the first and second page.
However, if page_size = 2, the first 2 records are different, and so are the next 2.

My queryset only returns unique objects, which is how I noticed the bug in the first place.
It is as though the second record is replacing the first.

**Comment by dimitrovskif** [comment] 2015-11-19 19:17
Hi, I just wrote a simple test and I cannot replicate your problem. Since the `page_size` is equal to 1, every n-th page shows the n-th element in the queryset. Therefore, the first page and the second page contain two different records (Book#0 and Book#1 in my example)

models.py:
```python
from django.db import models

class Book(models.Model):
    name = models.CharField(max_length=50)

```

tests.py:
```python
from django.test import TestCase
from rest_framework import serializers, generics, pagination, test
from . import models


class BookSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.Book
        
class BookPagination(pagination.PageNumberPagination):
    page_size = 1

class BookView(generics.ListAPIView):
    serializer_class = BookSerializer
    pagination_class = BookPagination
    
    def get_queryset(self):
        return models.Book.objects.all()

class PaginationTest(TestCase):
    def setUp(self):
        self.factory = test.APIRequestFactory()
        for n in range(10):
            book = models.Book(name='The book #%i' % n)
            book.save()
            
    def test_pages(self):
        test_view = BookView.as_view()
        
        for n in range(1, 5):
            print('Querying the %i-th page...' % n)
            req = self.factory.get('/?page=%i' % n)
            response = test_view(req)
            response.render()
            print('%s\n' % response.content)
        
        
```

**Comment by tomchristie** [comment] 2015-11-19 19:21
Okay. Going to close this for now. There may be something behind this, but if so then we need a reproducible case first. Perhaps simple steps to reproduce might help here?

**Closed by tomchristie** 2015-11-19 19:22 UTC
Labels: Needs further review
