### ISSUE TITLE
APIClient raises AttributeError exception: object has no attribute 'serializer'

### ISSUE THREAD

**Issue by AlexDoul** [tomchristie/django-rest-framework#2903] opened 2015-05-04 17:58 UTC
Testing this kind of view thru the APIClient:

```python
class TestApiView(APIView):
    def get(self, request, format=None):
        return Response(status=status.HTTP_404_NOT_FOUND)
```

raises Exception

> AttributeError: 'NoneType' object has no attribute 'serializer'.

Same situation with views which are based on mixins.ListModelMixin.
Examples with tracebacks on stackoverflow: http://stackoverflow.com/questions/29976003/django-rest-framework-attributeerror-object-has-no-attribute-serializer

**Comment by xordoquy** [comment] 2015-05-04 18:08
It looks like the Response representation assume there's a serializer.

**Comment by tomchristie** [comment] 2015-05-05 08:22
The exception here is being raised by HTMLFormRenderer.
Closing this as a duplicate of #2773

**Closed by tomchristie** 2015-05-05 08:22 UTC
Labels: Enhancement
