### ISSUE TITLE
FileUploadParser not compatible with Django Upload Handlers

### ISSUE THREAD

**Issue by cyalangi** [tomchristie/django-rest-framework#4292] opened 2016-07-21 07:34 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
- Define a POST view to use FileUploadParser 
- Use curl to upload a 100 byte text/plain file.
The [line 149](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/parsers.py#L149) in parsers.py is buggy. It is expecting a return value from handle_raw_input. MemoryFileUploadHandler::handle_raw_input() doesn't return anything. Django FileUploadHandler::handle_raw_input() doesn't return any value.

## Expected behavior
Handle the uploaded file

## Actual behavior
Throws the following error
FileUpload parse error - none of upload handlers can handle the stream

**Comment by xordoquy** [comment] 2016-07-21 10:57
You'll need to be more specific with your curl commande as it's probably sent as multipart

**Comment by cyalangi** [comment] 2016-07-21 18:32
The request body was not sent as multipart. Here is the curl command I used.

`curl -X POST http://localhost:8000/internal -H "Content-Type: text/plain; chartset utf-8" --data-binary @./datafile.csv`

Here is the corresponding HTTP request 

```
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /internal HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.43.0
> Accept: */*
> TOKEN: ###
> Content-Type: text/plain; charset=utf-8
> Content-Length: 328
> 

```

If you refer to the code line I mentioned in the bug description you can see that handle_raw_input() doesn't return any values.

**Comment by tomchristie** [comment] 2016-08-01 16:35
Note that our behavior of `handle_raw_input` is the same as Django's.

REST framework: https://github.com/tomchristie/django-rest-framework/blob/3.4.1/rest_framework/parsers.py#L149
Django: https://github.com/django/django/blob/1.9.8/django/http/multipartparser.py#L128

**Comment by tomchristie** [comment] 2016-08-01 16:47
This is actually caused by a different issue than originally reported. Believe this to in fact be a duplicate of #3610.

**Closed by tomchristie** 2016-08-01 16:47 UTC
Labels: Needs further review
