### ISSUE TITLE
Preventing display of microseconds when using iso8601

### ISSUE THREAD

**Issue by lukeburden** [tomchristie/django-rest-framework#3380] opened 2015-09-09 17:47 UTC
Hi there,

I'm using iso8601 for date representation but want to prevent microseconds from being displayed.
I've created my own DateTimeField with an overridden to_representation and injected it as a default field in my own ModelSerializer subclass.

```python
class DateTimeField(serializers.DateTimeField):
    def to_representation(self, value):
        value = value.replace(microsecond=0)
        return super(DateTimeField, self).to_representation(value)

class ModelSerializer(serializers.ModelSerializer):
    serializer_field_mapping = copy(serializers.ModelSerializer.serializer_field_mapping)
    serializer_field_mapping[models.DateTimeField] = DateTimeField

```

All good and works, but kind of a lot of shuffling of code to get something so simple done and it strikes me that the vast majority of the time users won't need microsecond precision on their APIs. Thoughts were:
* a setting to prevent microsecond precision being rendered, but this doesn't play well with the datetime format settings in general
* allowing `DATETIME_FORMAT` setting to point to a callable, and test for this in DateTimeField.to_representation

@tomchristie, how would you like to see this done, if at all?

**Comment by xordoquy** [comment] 2015-09-09 19:57
You simply need the DATETIME_FORMAT settings to be iso8601 strftime string without microsecond.

**Comment by lukeburden** [comment] 2015-09-09 20:39
Thanks for your quick response. I'd have taken that obvious route if I could have.

The issue there is the format specifiers python's strftime supports for timezones. There are two related specifiers, and neither output the timezone in colon separated form. Ie, "+07:00" as the Datetime.isoformat() method does. Yes, the form supported without the colon ("+0700") is still technically iso8601, but I cannot make this change without most probably breaking API clients. Not having fine control over this without extensive subclassing is less than ideal IMHO.

**Comment by xordoquy** [comment] 2015-09-09 21:07
Fair enough

**Comment by tomchristie** [comment] 2015-09-10 08:53
So, assuming I know nothing about the framework...

* What does the default output format look like?
* What *can* we change it too using the settings?
* What *can't* we change it too using the settings?
* What does the output of your custom field look like?

**Comment by xordoquy** [comment] 2015-09-10 09:31
The very root cause is that you can't write an iso8601 with Python's strftime. I'm temped to raise an issue on Python's bug tracker.

**Comment by xordoquy** [comment] 2015-10-02 12:24
OK, after reviewing this, I'm closing it for the following reasons:
- ISO8601 format allows a timezone format that is compatible with strftime/strptime (the +/-HHMM format):
https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC
- DRF already allows custom formats through strftime/strptime.
- You can use a dedicated field for really specific formats.
- The extra work to do / maintain very specific formats isn't worth against the very specific issue.

**Closed by xordoquy** 2015-10-02 12:24 UTC
Labels: Enhancement

**Comment by lukeburden** [comment] 2015-10-02 19:52
Yeah, fair enough. It's not super reasonable to expect DRF to be the component that takes responsibility for a limitation in python's strftime.
