### ISSUE TITLE
All browsable api form POSTs failing with "This field is required", even if data is provided

### ISSUE THREAD

**Issue by jonathan-golorry** [tomchristie/django-rest-framework#3588] opened 2015-11-03 23:03 UTC
I have djangorestframework 3.2.4 and django 1.8.5 installed globally and everything is working fine from that environment.

If I create an environment with djangorestframework 3.3.0 and django 1.8.5, the exact same project with the same local db works until I try to post a form from the browsable api. The POST fails with "This field is required", even if there was data. All I've tested so far is POSTing from the HTML form, but this occurs even in the most basic tutorial.

**Comment by alexander-ae** [comment] 2015-11-04 03:40
I have djangorestframework 3.3.0 and django 1.9b1

same problem here

**Comment by xordoquy** [comment] 2015-11-04 07:07
Isn't this related to #3578 ?

**Comment by xordoquy** [comment] 2015-11-04 07:23
I need more informations to reproduce, I gave 3.3.0 a go with browsable API and it works here (tm).
Could you can with a simplest basic failing example or test case ?

**Comment by xordoquy** [comment] 2015-11-04 09:53
OK, I could reproduce it with an  authenticated user.
Without authentication it would just work fine.

**Comment by xordoquy** [comment] 2015-11-04 10:13
Closing this as duplicate of #3588
Tests are showing the serializer.data is an empty dict.

**Comment by tomchristie** [comment] 2015-11-04 10:14
> Closing this as duplicate of #3588

This *is* #3588?

**Closed by xordoquy** 2015-11-04 10:13 UTC
Labels: Bug
