### ISSUE TITLE
Regression Model.get_FOO_display() doesn't work with the last version

### ISSUE THREAD

**Issue by stunaz** [tomchristie/django-rest-framework#4625] opened 2016-10-25 12:30 UTC
Hi, Here is the doc to [get_FOO_display](https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.get_FOO_display)

Having a model like this
```python
class Person(models.Model):
    SHIRT_SIZES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
    )
    name = models.CharField(max_length=60)
    shirt_size = models.CharField(max_length=2, choices=SHIRT_SIZES)
```

I could have a serializer field to get the shirt sizes name as  :
```python
shirtSizeName = serializers.CharField(source='get_ shirt_size_display', required=False, read_only=True)
```

Here is what I get with drf 3.5.x: `<bound method Person._curried of < Person: Person object>>`

it is working with drf 3.4.7 but not with django 3.5.x
django 1.10.2

**Comment by johnraz** [comment] 2016-10-25 13:25
I think this is a duplicate of #4602

**Comment by xordoquy** [comment] 2016-10-25 13:36
Thanks @johnraz I failed at finding that one.

**Closed by xordoquy** 2016-10-25 13:36 UTC
