### ISSUE TITLE
Upgrading to Django 1.9 breaks login/logout dropdown of admin & api browser

### ISSUE THREAD

**Issue by mcastle** [tomchristie/django-rest-framework#3691] opened 2015-12-02 07:09 UTC
<img width="1173" alt="screen shot 2015-12-02 at 1 07 37 am" src="https://cloud.githubusercontent.com/assets/3880707/11524560/3e3f360e-9891-11e5-9bf7-c18b59fa172f.png">

**Comment by kevin-brown** [comment] 2015-12-02 09:21
This looks like a duplicate of https://github.com/tomchristie/django-rest-framework/issues/3545, an issue which should have been fixed in the 3.3.0 release

**Comment by xordoquy** [comment] 2015-12-02 09:24
Indeed, looks very similar.
Closing this assuming the DRF version is less than 3.3.1 and therefore doesn't support Django 1.9.
Feel free to reopen if I'm wrong about this.

**Closed by xordoquy** 2015-12-02 09:24 UTC

**Comment by mcastle** [comment] 2015-12-02 16:18
That's correct. This is with version 3.2.4. Will let you know if I see this after upgrading to 3.3.1.
