### ISSUE TITLE
'module' object has no attribute 'DecimalValidator' When using DecimalField

### ISSUE THREAD

**Issue by mrgaolei** [tomchristie/django-rest-framework#3580] opened 2015-11-02 08:52 UTC
version 3.2.x is OK,
When I upgrade to 3.3, is broke.

**Comment by xordoquy** [comment] 2015-11-02 09:44
We need more context or better a failing test case to understand what's going on.

**Comment by xordoquy** [comment] 2015-11-02 09:58
Duplicate of #3568

**Closed by xordoquy** 2015-11-02 09:58 UTC
Labels: Needs information
