### ISSUE TITLE
Why doesn't it have a request form on browse api? (DRF3)

### ISSUE THREAD

**Issue by TonyPythoneer** [tomchristie/django-rest-framework#3722] opened 2015-12-11 05:47 UTC
This is my screen. Originally, DRF2 has a form under the returned data.

But DRF3 hasn't the form, why? how do I enable the form?

![drf3](https://cloud.githubusercontent.com/assets/10459119/11736657/ba5780e4-a00b-11e5-9ce5-8a209b96211a.png)

**Comment by xordoquy** [comment] 2015-12-11 05:59
Since GET isn't allowed you won't have the form.

Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by TonyPythoneer** [comment] 2015-12-11 06:31
Thanks!

**Comment by debnet** [comment] 2015-12-11 15:49
Reviewed with @xordoquy, it's definitly a bug and/or a regression.

The form doesn't show even with POST or GET only api_views making BrowsableAPI completly useless.

**Comment by dimitrovskif** [comment] 2015-12-13 12:28
Which view is this? `rest_framework.authtoken.views.ObtainAuthToken`?

**Comment by TonyPythoneer** [comment] 2015-12-14 02:17
I had reviewed DRF tutorial. According to document, the view needs to set a class variable to `serializer_class`, so it will display the request form. And, only generic api view and viewset have this features. I currently never try api view it can do or not.

**Comment by debnet** [comment] 2015-12-14 09:12
JSONField currently displayed in previous versions of DRF (3.2.5).

**Comment by tomchristie** [comment] 2016-10-11 12:56
Closing this given the age of the issue. Happy to reopen if anyone can confirm that this is currently an issue. (Please include reproducible example or similar)

**Closed by tomchristie** 2016-10-11 12:56 UTC
Labels: Needs confirmation
