### ISSUE TITLE
select_related and prefetch_related should only cache on GET method

### ISSUE THREAD

**Issue by sainttail** [tomchristie/django-rest-framework#3028] opened 2015-06-11 09:26 UTC
I'm following [#1964](https://github.com/tomchristie/django-rest-framework/issues/1964) 

by declaring something like `queryset = SomeObj.objects.all().prefetch_related('many_object')` in Generic Viewset

However this also cache when I patch the object and adding or removing that `many_object`
so I have to override patch method to called `get_object()` to refresh in order to get the updated return result

```
...
instance = self.get_object()
return Response(self.get_serializer(instance).data)
```

Are there any method to separate this?

**Comment by tomchristie** [comment] 2015-06-23 12:15
Duplicate of #2442. Not a lot we can do about this other than suitable documentation.
You could override `get_queryset` to only perform the prefetch on GET requests, perhaps?

**Closed by tomchristie** 2015-06-23 12:15 UTC
