### ISSUE TITLE
SerializerMethodFields skipped in ModelSerializer(None)

### ISSUE THREAD

**Issue by Anonymooseable** [tomchristie/django-rest-framework#2956] opened 2015-05-21 14:04 UTC
When None is passed into a `ModelSerializer` which has `SerializerMethodField`s defined, these fields will be skipped in its data:

```python
class SomeModel(models.Model):
  pass

class SomeModelSerializer(serializers.ModelSerializer):
  def get_one(self, obj):
    return 1
  one = SerializerMethodField()
  class Meta:
    model = SomeModel
    fields = ('one',)

# SomeModelSerializer(None).data = {}
# SomeModelSerializer(SomeModel()).data = {'one': 1}
```

This seems somewhat incongruous to me, I would expect it to still call the method.

The behaviour is caused by the `Serializer` falling back to `get_initial()`, which skips over the read-only SerializerMethodField.

**Comment by tomchristie** [comment] 2015-05-21 14:15
This isn't intended usage, so not sure that we'll keep this open, but all the same...

> The behaviour is caused by the Serializer falling back to get_initial(), which skips over the read-only SerializerMethodField.

Could you point out what you mean a little more explicitly?
Thanks!

**Comment by Anonymooseable** [comment] 2015-05-21 14:27
The `data` property of a Serializer will fall back to `get_initial` [here](https://github.com/tomchristie/django-rest-framework/blob/3.1.2/rest_framework/serializers.py#L217) in this scenario, and that, in turn, [skips over read_only fields](https://github.com/tomchristie/django-rest-framework/blob/3.1.2/rest_framework/serializers.py#L347).

**Comment by tomchristie** [comment] 2015-05-21 14:35
Yeah - afraid we'll be closing this of.
Passing `None` is intistinguishable to us to not passing any instance.
The intended behavior in that case is to provide a templated initial data case that can be used eg. to pre-fill the POST content box in the browsable API. Changing that to also include read only fields would then be incorrect.

**Closed by tomchristie** 2015-05-21 14:35 UTC

**Comment by Anonymooseable** [comment] 2015-05-21 14:42
Alright, thanks!
