### ISSUE TITLE
Serializer.__repr__ has side effects

### ISSUE THREAD

**Issue by staab** [tomchristie/django-rest-framework#3196] opened 2015-07-29 20:26 UTC
`utils.representation.serializer_repr` calls `Serializer.fields`, which is lazily evaluated. This is in turn called by `Serializer.__repr__`. So a simple print statement can cause data to be calculated.

This isn't great, but may not be itself a bug. I'm running into something slightly different - a nested serializer appears to not be having `fields` called on it at all. If I print the field, it shows up nested in the response; if I don't print it, it does not. This is my own programming error, but it was very hard to track down, and I thought I should bring this up.

**Comment by tomchristie** [comment] 2015-07-29 21:11
Okay fair enough. I don't see anything actionable here, so going to close this off for now. Lazily evaluated properties are reasonable enough, so unless there's a specfic bug to deal with I'm not too bothered.

**Closed by tomchristie** 2015-07-29 21:11 UTC

**Comment by tkhyn** [comment] 2016-09-01 11:32
Hello, I just spend hours finding out why my code behavior depended on whether I had a breakpoint in the __init__ of a Serializer subclass.

**Comment by tkhyn** [comment] 2016-09-01 13:09
Hello and thanks @tomchristie for all your work on DRF, 

I've just spent hours figuring out why the behavior of my code depended on whether I had a breakpoint in my `Serializer` subclass' `__init__` ... and it turns out the problem came from the fact the IDE (I'm using PyCharm) always calls `__repr__` on `self` when it stops in `__init__`, triggering the calculation of lazy attributes which source values (thinking of `self.fields`) are modified in my `__init__` call ...

As the root cause was not obvious I could not find any information on that problem until I found the root cause myself ... which made me land here. Now I know that a simple method override solves the issue, but this has been a quite frustrating experience. So if it is possible to spare future users that frustration, that would, in my opinion, be great!

I personally do not use the information that is provided by `Serializer.__repr__`. The class name is usually enough, and in the rare occasions I need more info it's easy enough with a good debugger / IDE or even a one-liner. So I would be perfectly happy with a minimal `__repr__` that would not depend on lazily calculated values. And the full-featured `__repr__` (and possibly its depth as mentioned in #2834) could be enabled using a specific setting.

It should not be too hard to do so if you're happy with something like that and if I can find a bit of time I could submit a PR implementing the idea.

**Comment by tomchristie** [comment] 2016-09-01 16:08
This'd need to start for a position of "here's what a user might do, here's why the behaviour is problematic".

Right now it's not specific enough to be properly actionable.

**Comment by tkhyn** [comment] 2016-09-01 21:26
> here's what a user might do, here's why the behaviour is problematic

I know, this is an edge case. Bugs and strange behaviors usually occur on edge cases. However in this particular case I'm doing exactly what is described and recommended in [the doc](http://www.django-rest-framework.org/api-guide/serializers/#example). The only thing I have done to trigger the strange / buggy behavior was to add a breakpoint somewhere in that `__init__` method.

As this issue can be encountered in a relatively normal situation (following the doc + debugging), and as the solution is not obvious / self-explanatory, I would tend to consider it worth fixing.

Now that I know that I have spent hours to figure out that I 'just' needed to monkey-patch the methods in the ``representation`` module it's ok for me and life will go on. I was just thinking it could make the lives of other users (including those in #2834) a bit easier.

Maybe a warning in the doc with the example mentioned above could be enough, though.

**Comment by tomchristie** [comment] 2016-09-02 08:36
> I'm doing exactly what is described and recommended in the doc. The only thing I have done to trigger the strange / buggy behavior was to add a breakpoint somewhere in that __init__ method.

Okay, so specifically, what? I'd just like this nailed do to a more specific example, so we can make a better judgement call on it.

**Comment by tkhyn** [comment] 2016-09-02 10:16
All right, let's be more specific then. Using the documentation example, let's put a breakpoint on the first line of `__init__` and run a code that creates an instance `s` of  `DynamicFieldsModelSerializer`:

- the debugger pauses the code on the breakpoint
- the IDE calls `s.__repr__`
- `s.__repr__` in turns calls `representation.serializer_repr`
- `serializer_repr` evaluates `s.fields` and therefore `s._fields`
- `serializer_repr` also evaluates `s.validators` which calls `s.get_validators` which calls `s.get_unique_together_validators` as `s` is a `ModelSerializer` subclass instance
- `s.get_unique_together_validators` evaluates `self._writable_fields` ([here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L1400)), which is now cached. Its value won't reflect any change made to `s.fields` in the next lines of `s.__init__`

If the program is resumed, and `s.to_internal_value` is called at some point, `s._writable_fields` does not have the correct value, and that leads to a wrong `validated_data`, for example.

This is the issue I encountered. There may or may not be other similar problems caused by the use of computed values by `Serializer.__repr__` (like the one reported by the OP).

**Comment by kevin-brown** [comment] 2016-09-02 15:03
> If the program is resumed, and s.to_internal_value is called at some point, s._writable_fields does not have the correct value, and that leads to a wrong validated_data, for example.

If I'm reading this properly, you can reproduce the issue within a test by having a custom serializer that overrides `__init__` and calls `repr(self)` within it?

If that can trigger the issue you described, it might be useful to have that test case built out as a reference.

**Comment by tomchristie** [comment] 2016-09-02 15:58
Not really fussed about having a test case for this.

I've got *some* sympathy towards the "__repr__ should avoid calling into lazily evaluated properties". However, on balance I'd think that the positive debugging aspects of ModelSerializers displaying the fields they generate outweighs the negative aspects.

Open to reconsidering at some point, but not convinced at the moment, unless someone else can present a compelling solution.

**Comment by tkhyn** [comment] 2016-09-03 01:52
>  you can reproduce the issue within a test by having a custom serializer that overrides __init__ and calls repr(self) within it?

Yes. I think I did that at some point when I was getting closer to finding out what was going on.

> I'd think that the positive debugging aspects of ModelSerializers displaying the fields they generate outweighs the negative aspects.

Well, I'd tend to respectfully disagree, because when debugging changes the behavior it makes it a bit harder to debug!

After a short dive in the code, here is another idea to keep the current behavior and solve the issue:

1. add `@fields.setter` that would `delete self._writable_fields`, `delete self._writable_fields` and `delete self._validators`
2. and either:
  - state in the documentation that `ModelSerializer.fields` should not be changed in place but set to a new value instead
  - use a `MutableMapping` subclass instead of a `dict` for `self._fields`. Use `pop`, `__setitem__`, `update`, etc ... to delete `_writable_fields`, `_readable_fields` and `_validators` (or even modify them accordingly but I don't think the performance would improve much, and it's probably too complicated to do for `_validators`)

**Comment by tomchristie** [comment] 2016-09-03 06:01
Re-reading this and...

> If I'm reading this properly, you can reproduce the issue within a test by having a custom serializer that overrides __init__ and calls repr(self) within it?

Second pass around I agree with this. Yup if you can demonstrate that calling __repr__ within __init__ results in incorrect serializer behaviour, then there may be something we can act on.

That'd be a concrete case to work with.
