### ISSUE TITLE
HTML sometimes returned when `Accept: application/json` is provided

### ISSUE THREAD

**Issue by pmdarrow** [tomchristie/django-rest-framework#3362] opened 2015-09-03 14:52 UTC
DRF returns HTML in a few different places even when the `Accept: application/json` header is provided. Examples:

* When `DEBUG=True` and I make a request that returns a 500, I'll get Django's debug page and not a nicely formatted JSON response. 
* When `DEBUG=False` and I make a request that returns 404 (outside of DRF-managed urls) or 500, the default 404.html or 500.html templates are returned. 

It would be nice to have optional settings and/or handlers provided that could be enabled to always return JSON when `Accept: application/json` is provided.

**Comment by kevin-brown** [comment] 2015-09-03 16:12
I'm going to close this off as being "not (realistically) possible" and "can be done on your own".

> When DEBUG=True and I make a request that returns a 500, I'll get Django's debug page and not a nicely formatted JSON response.

This is Django's exception handling kicking in because we do not handle all exceptions in our exception handler. You can override the [exception handler](http://www.django-rest-framework.org/api-guide/exceptions/) if you want to handle custom exceptions.

DRF tries to handle the most common exceptions (all API errors, validation errors, Django's 404, etc.), but it leaves any uncommon ones up to you to handle.

> outside of DRF-managed urls

In order to handle errors that happen outside of DRF-managed urls, DRF would have to have the error handler operating on the middleware level. Right now DRF handles exceptions within the custom `APIView` (and subclasses) so it doesn't interfere with other parts of your application.

Here's an example of where that could be an issue: You're using an XML renderer, so you want exceptions to be rendered in XML. But you completely forget that most browsers explicitly send `application/xml` before `*/*`, so now anyone looking to use your HTML pages gets an XML error message instead of your custom error page. And if they didn't get an XML error, they would probably see a Browsable API error if you have that enabled.

**Closed by kevin-brown** 2015-09-03 16:12 UTC

**Comment by pmdarrow** [comment] 2015-09-05 21:18
I think an error handler than could be optionally turned on at the middleware layer would be a good thing to have. I created this issue after @tomchristie recommended I do so, so it would be nice to get his input on this.

**Comment by pmdarrow** [comment] 2015-09-14 16:03
@tomchristie any thoughts?

**Comment by tomchristie** [comment] 2015-09-15 08:11
On reflection going to second @kevin-brown here, *at least for the moment*. I think the assessment might change in the future, but okay with the status quo for now.

**Comment by cnobile2012** [comment] 2018-01-31 16:32
I have run into this issue many times with different APIs I have dealt with. A supposedly RESTful API returns HTML when a 404 is returned. There needs to be a better way of traping these types of errors. Of cause there are two different types of 404 errors, right? One that is caused by using an invalid URI and the other caused by not finding an object in the database. The second is fairly easy to handle, but the first would probably need some sort of middleware.

This issue is over two years old at the time of my comment, but could this be looked into again at this time. Maybe an optional middleware?

**Comment by tomchristie** [comment] 2018-02-01 15:02
@cnobile2012 - Tracked against https://github.com/encode/django-rest-framework/issues/4556

We could consider milestoning it, yes.
