### ISSUE TITLE
Regression implementing custom pagination upgrading to 3.2.0 (from 3.1.3)

### ISSUE THREAD

**Issue by arw180** [tomchristie/django-rest-framework#3284] opened 2015-08-17 18:59 UTC
I was implementing some bare-bones custom pagination of sorts that worked fine in 3.1.3 but is now broken since updating to 3.2.0 (FWIW it's also broken in 3.2.2). If there was an API change, I haven't been able to find it in the code or the docs.  

Relevant code snippets:  

views.py:
```
class ListingSearchViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.ListingSerializer
    filter_backends = (filters.SearchFilter, )
    search_fields = ('title', 'description', 'description_short',)
    pagination_class = None

def get_queryset(self):
        filter_params = {}
        limit = self.request.query_params.get('limit', False)
        offset = self.request.query_params.get('offset', False)
        if limit:
            filter_params['limit'] = limit
        if offset:
            filter_params['offset'] = offset
        return model_access.filter_listings(self.request.user.username,
            filter_params)

    def list(self, request):
        return super(ListingSearchViewSet, self).list(self, request)
```
model_access.py:
```
def filter_listings(username, filter_params):
    objects = models.Listing.objects.for_user(username).all()
    # enforce any pagination params
    if 'offset' in filter_params:
        offset = int(filter_params['offset'])
        objects = objects[offset:]

    if 'limit' in filter_params:
        limit = int(filter_params['limit'])
        objects = objects[:limit]
    return objects
```

In all versions since 3.1.3, I get the following error when invoking this endpoint: `AssertionError: Cannot create distinct fields once a slice has been taken.`. If I remove the line that does the limiting (`objects = objects[:limit]`), I don't get the assertion error. Offset seems to behave in a similar manner.

**Comment by tomchristie** [comment] 2015-08-19 11:07
Not clear to me how it'd be a regression from 3.1.3 to 3.2.0, but looks to a be related to `SearchFilter` (which is where `.distinct()` ends up being used) and pagination. Again - unclear why there'd be any *change* there.

**Comment by arw180** [comment] 2015-08-19 17:31
The problem seems to stem from this change: https://github.com/tomchristie/django-rest-framework/commit/de95598a1ed7f1b609b9dbc6415655be65fae4a8#diff-01f357e474dd8fd702e4951b9227bffcR114

If I remove the `.distinct()`

**Comment by carltongibson** [comment] 2015-08-19 18:27
Wow. That's quite gnarly. 

 #2935, #3103 were about Oracle. There is an argument that touching the `else` branch was out of scope.

Calling distinct should be faster than hitting the DB twice and using `set` in Python. But maybe that's a false promise: if speed is an issue you're not going to **search** using the ORM...

**Comment by tomchristie** [comment] 2015-08-19 20:26
What's odd there is that 'distinct()' was also being used before that change tho.

(Also I shoulda been stricter in forcing the pr to not change the existing style outside of the oracle branch)

Are you able to replicate this in a test case? What database are you using here?

**Comment by carltongibson** [comment] 2015-08-19 20:31
The `distinct` call is [only on the Oracle side](https://github.com/tomchristie/django-rest-framework/commit/de95598a1ed7f1b609b9dbc6415655be65fae4a8#diff-01f357e474dd8fd702e4951b9227bffcL111) of the branching — in the first `if`— that's why it's so _gnarly_.

**Comment by tomchristie** [comment] 2015-08-20 08:22
The distinct is only on the *not oracle* side. One ugly thing about the pull request is that it happens to invert the `==` to `!=` which makes the diff more confusing to parse.

**Comment by carltongibson** [comment] 2015-08-20 08:36
Entirely. (I think are "_only_"s are talking about different before/afters...) Anyhoooo... @arw180 what's your smallest reproduce case look like?

**Comment by carltongibson** [comment] 2015-08-20 08:45
> The distinct is only on the not oracle side.

Oh. You're right. In which case it's extra curious.

**Comment by tomchristie** [comment] 2015-08-20 10:32
Righty,

I believe the reason you're seeing this now is that the `distinct()` call is now always being applied (rather than only if there are search parameters).

I've applied some refactoring here to ensure this isn't actually the case but this doesn't actually resolve the issue, because you will still see a problem on *either* version if you have search parameters.

The root cause here is actually that you're incorrectly applying pagination to the queryset *before* the search filtering has been applied. (You'll end up with incorrect pagination in the presence of search filters this way) Really you need to do so afterwards.

Either:

* Use the built-in LimitOffsetPagination instead.
* Apply your pagination filtering in `filter_queryset()`, after first calling super, instead of applying it in `get_queryset()`

**Closed by tomchristie** 2015-08-20 10:32 UTC
Labels: Needs further review

**Comment by arw180** [comment] 2015-08-20 11:38
The built-in `LimitOffset` pagination works great - it looks like the pagination is applied at the very end of the chain (i.e. applied after `get_queryset` and any additional filters you provide) - for some reason I had it in my mind that it would happen earlier, thus requiring me to implement my own since I was overriding `get_queryset` and all. Anyway, thanks for setting me straight, and thanks for this awesome framework!

**Comment by tomchristie** [comment] 2015-08-20 11:40
Cheers! :smile:
