### ISSUE TITLE
Auto-fill json post form with default template for browsable api

### ISSUE THREAD

**Issue by youneschaoui** [tomchristie/django-rest-framework#4858] opened 2017-01-27 16:02 UTC
It would be greate if we could have a possibility to auto-fill post form with default json object for browsable api

**Comment by kevin-brown** [comment] 2017-02-01 23:15
This is a duplicate of https://github.com/tomchristie/django-rest-framework/issues/2150.

**Closed by kevin-brown** 2017-02-01 23:15 UTC

**Comment by youneschaoui** [comment] 2017-02-08 11:44
It's not a duplicate since #1250 asks for remembering but I ask for specifying one time static json object like Postman client does.

**Comment by tomchristie** [comment] 2017-02-08 12:50
For now I'm going to treat this as out-of-scope. I do think we might address this kind of requirement in the future, but it's more likely to happen as part of a bigger re-thinking of the browsable API.
