### ISSUE TITLE
Missing DictField

### ISSUE THREAD

**Issue by qwiglydee** [tomchristie/django-rest-framework#2402] opened 2015-01-12 06:47 UTC
Is there any reason why there exists ListField, but no DictField?

There is https://github.com/estebistec/drf-compound-fields indicating need of such stuff.

**Comment by carltongibson** [comment] 2015-01-12 08:38
@qwiglydee Could you explain the case where you'd need this but wouldn't just use a nested serialiser?

**Comment by xordoquy** [comment] 2015-01-12 09:19
@carltongibson probably json fields though there are easier workaround for it.

**Comment by tomchristie** [comment] 2015-01-12 09:48
Duplicate of #2106, which I'm now retitling to make it more clear.

**Closed by tomchristie** 2015-01-12 09:48 UTC

**Comment by qwiglydee** [comment] 2015-01-12 21:46
I thought about native dict fields in mongodb/mongoengine.
But it is rather in focus of project django-rest-framework-mongoengine.

**Comment by tomchristie** [comment] 2015-01-13 08:57
DictField will support both.
The HStore mention is simply that Django's built-in HStore field will automatically be used in 1.8.
