### ISSUE TITLE
Browseable API should expose a form for filtering

### ISSUE THREAD

**Issue by thedrow** [tomchristie/django-rest-framework#2415] opened 2015-01-14 07:44 UTC
If using the ```DjangoFilterBackend``` you have a form will can be used in order to filter the response.
We can render that form on the browsable API in order to allow users to filter the results using UI instead of typing in querystrings.

**Comment by carltongibson** [comment] 2015-01-14 08:01
I'm +1 to this in principle — it sounds a nice addition. Without the second coffee I'm not sure what it would look like.

**Comment by carltongibson** [comment] 2015-01-14 08:33
@thedrow do you already have an idea of the change to support this? (Is it as simple as outputting the form on the filter we already have, or is there more?)

**Comment by tomchristie** [comment] 2015-01-14 08:43
Agreed, but duplicate of existing #2180

**Closed by tomchristie** 2015-01-14 08:43 UTC
Labels: Needs information

**Comment by carltongibson** [comment] 2015-01-14 08:48
Ah yes, forgot about that one.

**Comment by thedrow** [comment] 2015-01-14 10:13
Sorry about the duplicate. I did not see that issue before.
@carltongibson It's probably a matter of rendering the form.
