### ISSUE TITLE
Removing _closable_objects for pickling breaks response processing

### ISSUE THREAD

**Issue by chibisov** [tomchristie/django-rest-framework#1850] opened 2014-09-08 06:53 UTC
Here `_closable_objects` was added to `rendering_attrs` https://github.com/tomchristie/django-rest-framework/commit/59d0a0387d907260ef8f91bbbca618831abd75a3#diff-21a03cd19b8422c334c33ec8da66e9c8R21

Every rendering attribute is deleted in `__getstate__` method https://github.com/django/django/blob/1.7/django/template/response.py#L45

But `_closable_objects` is used in base response handler:
https://github.com/django/django/blob/1.7/django/core/handlers/base.py#L210

That's why after processing response from cache i get error like this:
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/web-chib/drf-ussie/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/Users/web-chib/drf-ussie/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/Users/web-chib/drf-ussie/lib/python2.7/site-packages/django/core/handlers/base.py", line 211, in get_response
    response._closable_objects.append(request)
AttributeError: 'Response' object has no attribute '_closable_objects'
```

I don't know, should i recreate this attribute by hand, or that's DRF error?

**Comment by lucacorti** [comment] 2015-01-30 19:40
I think there is a regression. I'm experiencing this again on 3.0.4 when using `cache_page()` on DRF views. Downgrading to 3.0.3 works.

**Comment by caisbalderas** [comment] 2015-01-30 20:12
thanks @lucacorti, confirming the regression on 3.0.4 I just had to downgrade

**Comment by jpadilla** [comment] 2015-01-30 21:26
@lucacorti @caisbalderas thanks for confirming.

@tomchristie Seems like f3b6eedb8aeaa23f4b48551356814837973db31c might have introduced the regression.

**Comment by tomchristie** [comment] 2015-01-30 21:35
Stupid assed pickle. Dumb way to cache responses. Grumble grumble.

**Comment by tomchristie** [comment] 2015-01-30 21:51
Rather than deleting _closable_objects in __getstate__ I guess if we replace it with an empty list that'd then work.

Bit tedious working around this clunkiness.

**Comment by tomchristie** [comment] 2015-01-31 08:29
So I assume the linked PR would resolve this, but we need to confirm.

**Comment by lucacorti** [comment] 2015-01-31 13:23
Works for me.

**Comment by tomchristie** [comment] 2015-01-31 14:30
Ok, merged. A test case would be helpful, but not going to consider that a blocker.

**Closed by tomchristie** 2015-01-31 14:30 UTC
Labels: Bug

**Comment by thebenwaters** [comment] 2015-02-14 22:18
I'm still having this error :(

**Comment by tomchristie** [comment] 2015-02-15 08:59
@thebenwaters want to give some minimal instructions to reproduce?

**Comment by thebenwaters** [comment] 2015-02-15 12:35
I can post more specific code tonight, but essentially instead of using a decorator like above I was using the cache.get low level within the post method of a viewset. Anytime that specific rest call was made it would throw the same error. Whenever the cache timed out it was fine, but when it was pulling from cache it would get the standard

```
Traceback (most recent call last):
  File "lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "lib/python2.7/site-packages/django/core/handlers/base.py", line 210, in get_response
    response._closable_objects.append(request)
AttributeError: 'Response' object has no attribute '_closable_objects'
```

**Comment by dnozay** [comment] 2015-03-17 22:40
Hitting this issue with `3.0.5` ...

```
======================================================================
ERROR: test_list_testcases (testruns.tests.UICallsApiTestcase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/damien/Work/dash/testruns/tests.py", line 25, in test_list_testcases
    response = self.client.get(url)
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/rest_framework/test.py", line 160, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/rest_framework/test.py", line 86, in get
    return self.generic('GET', path, **r)
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/rest_framework/compat.py", line 214, in generic
    return self.request(**r)
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/rest_framework/test.py", line 157, in request
    return super(APIClient, self).request(**kwargs)
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/rest_framework/test.py", line 109, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/django/test/client.py", line 426, in request
    response = self.handler(environ)
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/django/test/client.py", line 117, in __call__
    response.close()                    # will fire request_finished
  File "/Users/damien/Work/dash/tools-venv/lib/python2.7/site-packages/django/http/response.py", line 300, in close
    for closable in self._closable_objects:
AttributeError: 'Response' object has no attribute '_closable_objects'

----------------------------------------------------------------------
```

**Comment by xordoquy** [comment] 2015-03-17 23:05
@dnozay strange, there doesn't seem to be a regression on the response code.

**Comment by rosscdh** [comment] 2015-12-11 08:18
+1 having same issue

djangorestframework==3.3.1
django==1.8.4

**Comment by rosscdh** [comment] 2015-12-11 09:50
FYI: Seems to be being caused by rollbar

```
    # must come last
    'rollbar.contrib.django.middleware.RollbarNotifierMiddleware',
```

**Comment by Suor** [comment] 2016-12-15 12:40
Why is this closed? Picking-unpickling should not break the object.

**Comment by tomchristie** [comment] 2016-12-15 13:14
Because no-one's demonstrated that there's a regression. Looks feasible that it needs reopening, but let's start with a minimal reproducible case and take it from there.
