### ISSUE TITLE
Authorization:  expect 401 but got 200.

### ISSUE THREAD

**Issue by HelloYie** [tomchristie/django-rest-framework#4139] opened 2016-05-23 04:37 UTC
I have a protected-url, I use `authentication_classes = (JSONWebTokenAuthentication,)`, when I add a `Authorization: xxx` header:

```
 curl -H "Authorization: JWT <your_token>" http://localhost:8000/protected-url/
```
It return 401, work fine.

But, when delete `Authorization: xxx` and visit it directly.

```
 curl  http://localhost:8000/protected-url/
```
I got a 200 (a empty result ), It is a proteced url,  I want it return http 401.

**Comment by xordoquy** [comment] 2016-05-23 05:15
You are confusing Authentication and Authorization.
Closing this due to the lack of actionable content.
Will reconsider reopening with a small isolated and reproducible example.

**Closed by xordoquy** 2016-05-23 05:15 UTC

**Comment by HelloYie** [comment] 2016-05-23 06:01
Hi @xordoquy!

### My settings.py:

```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    )
}
```

### My view.py:

```
class LoginCheckView(GenericAPIView):
    serializer_class = None
    authentication_classes = (JSONWebTokenAuthentication,)

    def get(self, request):
        user = self.request.user
        result = {
            'mobile': user.get_username(),
            'id': user.id
        }
        return Response(result, status=status.HTTP_200_OK)
```

### And When I visit it:

`curl http://localhost:8000/api/accounts/login_check/`

It shoud response `401 Unauthorized `,  but it return `200 ok`:
   + response:  `{"mobile":"","id":null}`, 
   + http status:  `200 ok`

### When I visit it with `Authorization: JWT <your_token>` header, it works fine:

` curl -H "Authorization: JWT some wrong token" http://localhost:8000/api/accounts/login_checkl/`

It works fine.
  + response: `{"non_field_errors":["Error decoding signature."]}`
  + http status: `401 Unauthorized`

**Comment by HelloYie** [comment] 2016-05-23 07:38
My fault... settings should add `DEFAULT_PERMISSION_CLASSES`

```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
}
```
