### ISSUE TITLE
DRF not using default language

### ISSUE THREAD

**Issue by famoraes** [tomchristie/django-rest-framework#3711] opened 2015-12-07 13:31 UTC
Hey Guys,

I'm facing a problem with the default language. In this particular project, the language is set as `pt-br` (Brazilian Portuguese). Django works as expected, but DRF still returning errors in English. I've tried to use the `LocaleMiddleware` without success (even the framework returning the correct language on `Content-Language` header). An example:

```python
In [1]: from django.utils import translation
In [2]: translation.get_language()
Out[2]: 'pt-BR'

In [3]: serializer = StudentSerializer(data=request.data)
In [4]: serializer.is_valid()
Out[4]: False

In [5]: serializer.errors
Out[5]: 
OrderedDict([('create_user', ['Este campo é obrigatório.']),
             ('first_name', ['This field may not be blank.']),
             ('birthdate', ['Este campo é obrigatório.']),
             ('gender', ['Este campo é obrigatório.']),
             ('address', ['Este campo é obrigatório.']),
             ('address_number', ['Este campo é obrigatório.']),
             ('neighborhood', ['Este campo é obrigatório.']),
             ('city', ['Este campo é obrigatório.']),
             ('phone', ['Este campo é obrigatório.'])])
``` 

As you see Django errors are working as expected, but for some reason, DRF errors (`first_name` field) are not being translated.

**Comment by xordoquy** [comment] 2015-12-07 13:39
We'll need a test case for that as I can't reproduce it.
Can you try to get the simpler example we could run to reproduce the issue ?

**Comment by famoraes** [comment] 2015-12-07 14:05
Hey @xordoquy.
I created a simple project that reproduce the issue https://github.com/famoraes/drf-default-language-test.
In order to reproduce this, send  `POST` to `/api/foo/` with the data `{"bar": ""}`. 
Let me know if you could test.

**Comment by xordoquy** [comment] 2015-12-07 14:12
Works as expected to me:

    curl http://localhost:8000/api/foo/ -d '{"bar": ""}'
    {"foo":["Este campo é obrigatório."],"bar":["Este campo é obrigatório."]}

Closing this unless we can reproduce it.

**Closed by xordoquy** 2015-12-07 14:12 UTC
Labels: Needs information

**Comment by famoraes** [comment] 2015-12-07 14:17
This is weird. Works with `curl` but not with Postman (or angularjs).
![image](https://cloud.githubusercontent.com/assets/4910050/11628981/70aef03a-9cdc-11e5-8cda-8d3d312ce098.png)

**Comment by xordoquy** [comment] 2015-12-07 14:19
Likely, can you spot postman headers ?

**Comment by famoraes** [comment] 2015-12-07 14:21
This is the HTTP code sent by postman:

`POST /api/foo/ HTTP/1.1
Host: localhost:8003
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: b9c7665b-1036-d75d-fc6b-f3395deff99c

{
    "bar": ""
}
`

But, try this (the same request using curl):
`curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: ee7f7964-c295-7b6b-7f82-77d07e742ece" -d '{
    "bar": ""
}' 'http://localhost:8003/api/foo/'`

**Comment by xordoquy** [comment] 2015-12-07 14:30
Slightly different from the original error but still in correct language:

    {"foo":["Este campo é obrigatório."],"bar":["Este campo não pode ser em branco."]}

**Comment by famoraes** [comment] 2015-12-07 14:36
Well, I don't know what to do. Thanks for your help  @xordoquy.

**Comment by devnine99** [comment] 2023-08-31 07:05
Add rest_framework to INSTALLED_APPS
