### ISSUE TITLE
ModelSerializers only check for fields being set when (de)serializing objects/generating the form for the browsable API

### ISSUE THREAD

**Issue by gcbirzan** [tomchristie/django-rest-framework#4702] opened 2016-11-24 09:39 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a model serializer with no fields in the meta and a read only viewset (this is only needed because of the browsable API).

## Expected behavior

An exception should be raised when this endpoint is accessed saying that you should pass a fields value. 

## Actual behavior

If there are no resources (and the viewset is readonly or format isn't api) get_fields() isn't called, which in turn doesn't raise the AssertionError. 

While this should be caught by proper tests, a naive test that just hits the endpoint to make sure the configuration is correct will not catch this error.

P.S. I've not included a test because I'm not sure this should be considered an error, but if you think it is, I can easily do it.

**Comment by tomchristie** [comment] 2016-11-24 09:56
Okay, so I can't reproduce that, and "get_fields() isn't called" looks incorrect to me too. Any chance  you've inherited from `serializer.Serializer` instead without noticing? Failing that could you demonstrate how to replicate?

```python
>>> class A(serializers.ModelSerializer):
...     class Meta:
...         model = User
... 
>>> a = A(instance={})
>>> a.data
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/tomchristie/GitHub/django-rest-framework/rest_framework/serializers.py", line 527, in data
    ret = super(Serializer, self).data
  File "/Users/tomchristie/GitHub/django-rest-framework/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/tomchristie/GitHub/django-rest-framework/rest_framework/serializers.py", line 479, in to_representation
    fields = self._readable_fields
  File "/Users/tomchristie/GitHub/basic-rest-framework/env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/tomchristie/GitHub/django-rest-framework/rest_framework/serializers.py", line 373, in _readable_fields
    field for field in self.fields.values()
  File "/Users/tomchristie/GitHub/django-rest-framework/rest_framework/serializers.py", line 359, in fields
    for key, value in self.get_fields().items():
  File "/Users/tomchristie/GitHub/django-rest-framework/rest_framework/serializers.py", line 980, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/tomchristie/GitHub/django-rest-framework/rest_framework/serializers.py", line 1053, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: (u"Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the A serializer.",)
```

**Comment by xordoquy** [comment] 2016-12-02 14:19
Closing this due to the lack of actionable content.
Will consider reopening with a failing test case.

**Closed by xordoquy** 2016-12-02 14:19 UTC
