### ISSUE TITLE
Type error in DjangoObjectPermissionsFilter on Python 3.4 : unorderable types: list() >= tuple()

### ISSUE THREAD

**Issue by bibenga** [tomchristie/django-rest-framework#4005] opened 2016-03-19 05:43 UTC
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Use latest version on django-guardian 1.4.2 
2. djangorestframework 3.3.3

on Python 3.4

File "/rest_framework/filters.py", line 309, in filter_queryset
  if guardian.VERSION >= (1, 3):
TypeError: unorderable types: list() >= tuple()

on Python 2.7

guardian.VERSION >= (1, 3) always False

currently in filters.py:309 -
        if guardian.VERSION >= (1, 3):

on python 2.7 always False

replace to - 
        if guardian.VERSION >= [1, 3]:

## Expected behavior

Filtered result

## Actual behavior

Exception occurred on Python 3.4
All object showed on Python 2.7

**Comment by xordoquy** [comment] 2016-03-19 10:02
At the moment our tests are run against Django-Guardian 1.3.2
I guess we could bump the version there and see if it still works.

**Comment by auvipy** [comment] 2016-03-29 20:49
same issue. I'm facing while upgrading drf-extensions to djano 1.9 drf 3.3.3 gurdian 1.4.2
rest_framework/filters.py", line 309, in filter_queryset
    if guardian.VERSION >= (1, 3):
TypeError: unorderable types: list() >= tuple()

**Comment by auvipy** [comment] 2016-03-29 20:50
https://github.com/django-guardian/django-guardian/commit/501695a190ff20aff13715311fd05062e67401c6

**Comment by auvipy** [comment] 2016-03-31 13:52
as far guardian the issue is actually django guardian specific and been fixed in master

**Comment by xordoquy** [comment] 2016-03-31 14:20
@auvipy thanks for reporting. I'm closing this issue, we'll bump the guardian version in some time.

**Closed** 2016-03-31 14:46 UTC
Labels: Enhancement

**Comment by auvipy** [comment] 2016-03-31 14:52
the fixed version is unreleased yet :/ facing lot of trouble with drf-extensions 1.9 support :(

**Comment by xordoquy** [comment] 2016-03-31 14:59
The thing is, if we change the tuple in favor of a list, we'll break already working guardians. I don't really see another solution here.

**Comment by auvipy** [comment] 2016-03-31 15:03
exactly

**Comment by KhasanovBI** [comment] 2016-05-26 16:16
We also had this error at production...

**Comment by tomchristie** [comment] 2016-05-26 19:23
Milestoning to increase the priority of this one.
