### ISSUE TITLE
JSONEncoded should coerce Decimals to string by default.

### ISSUE THREAD

**Issue by debnet** [tomchristie/django-rest-framework#2417] opened 2015-01-14 16:08 UTC
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/encoders.py#L45-L47

Converting Decimal to float is hasardous because floats internal representation can have more decimal than expected in the model.

For exemple the model field `price = models.DecimalField(max_digits=20, decimal_places=2)` and the following decimal `Decimal('874662070036053953.96')` will fail like this:

`{'price': ['Ensure that there are no more than 2 decimal places.']}`

**Comment by tomchristie** [comment] 2015-01-14 17:16
By default `DecimalField` will coerce the outgoing representation to a strict string value...

http://www.django-rest-framework.org/api-guide/fields/#decimalfield

JSONRenderer will only output floats if `COERCE_DECIMAL_TO_STRING` is set to `False` - in which case tests should also be making float comparisons. I wouldn't recommend the float representation in JSON, but some developers will want it for ease of use.

I don't *currently* believe that anything in that behavior listed above is incorrect or should be classified as a bug, but if I've misunderstood your issue then you're welcome to expand further and we could consider reopening if it really does seem like there's some unexpected behavior.

**Comment by xordoquy** [comment] 2015-01-14 17:25
@tomchristie JSONRenderer uses the JSONEncoder. The latter translate the Decimal to a float which leads to precision issues:
```
json.dumps(float(Decimal('874662070036053953.96')))
'8.74662070036054e+17'
```

**Comment by xordoquy** [comment] 2015-01-14 17:32
With the JSONEncoder:

```
import json
from decimal import Decimal
from rest_framework.utils.encoders import JSONEncoder

json.dumps(Decimal('874662070036053953.96'), cls=JSONEncoder)
# '8.74662070036054e+17'
```

**Comment by tomchristie** [comment] 2015-01-14 17:53
Yes,*if* you pass decimal instances to `JSONEncoder` then it'll treat them as floats - the right thing to do if you *don't* want that is to coerce them to strings first, which eg is what will happen if using `DecimalField` with a serializer.

**Comment by debnet** [comment] 2015-01-14 18:07
By the way, it seems the correct JSON representation of Decimal is string.

**Comment by xordoquy** [comment] 2015-01-14 18:26
Ok, seems to be working if we take the serializers into account.

```
import json
from decimal import Decimal
from rest_framework.utils.encoders import JSONEncoder
from rest_framework import serializers

class DecimalSerializer(serializers.Serializer):
    dec = serializers.DecimalField(max_digits=20, decimal_places=2)

d = DecimalSerializer(instance={'dec': Decimal('874662070036053953.96')})
d.data
# ReturnDict([('dec', u'874662070036053953.96')])
json.dumps(d.data, cls=JSONEncoder) == '{"dec": "874662070036053953.96"}'
```

**Comment by tomchristie** [comment] 2015-01-14 19:53
Actually have some more thoughts on this. Will comment more fully in due course.

**Comment by tomchristie** [comment] 2015-01-15 11:54
I think we should also apply the `COERCE_DECIMAL_TO_STRING` setting in the encoder, as well as the serializer field. That'll still allow devs to easily switch between float and string, but will mean that by default passing a Decimal directly to JSONRenderer will still end up as a string (unless `COERCE_DECIMAL_TO_STRING` has been set to false).

**Comment by tomchristie** [comment] 2015-01-19 14:03
Okay so I was planning on changing `JSONEncoder` to coerce to strings, if `api_settings.COERCE_DECIMAL_TO_STRING` was `True`. The idea there is that *as well* as that setting affecting the output of serializer fields, it would also be used by the encoder.
The problem with that approach is that it breaks folks trying to use `serializers.DecimalField(coerce_to_string=False)` and expecting to get a float JSON representation.

As a result I'm closing off this ticket again - if you want string representations in JSON then ensure that you're coercing decimals to strings. (Or rely on the standard serializer behavior)

**Closed by tomchristie** 2015-01-19 14:03 UTC
Labels: Enhancement

**Comment by thenewguy** [comment] 2015-09-05 04:54
@tomchristie Is this issue firmly resolved as WONTFIX?

It produces dangerous results when dealing with money for example...

**Comment by thenewguy** [comment] 2015-09-05 05:01
Simple example:
```
        from decimal import Decimal
        from django.utils.text import force_text
        return Response({
            "decimals-not-floats": [
                Decimal(float('1.1')),
                force_text(Decimal(float('1.1'))),
                self.estimate,
            ],
            
        }, status=status.HTTP_400_BAD_REQUEST)
```
to 
```
{
    "decimals-not-floats": [
        1.1,
        "1.100000000000000088817841970012523233890533447265625",
        "mo money mo problems"
    ]
}
```

**Comment by xordoquy** [comment] 2015-09-05 08:33
@thenewguy This is because your environment tricks you into thinking your decimal should be 1.1 while it actually should be 1.100000000000000088817841970012523233890533447265625.
In my Python shell, I have:
```
>>> Decimal(float('1.1'))
Decimal('1.100000000000000088817841970012523233890533447265625')
>>> force_text(Decimal(float('1.1')))
'1.100000000000000088817841970012523233890533447265625'
```

There are a couple of resource that will explain better than I'll do why you shouldn't be using float with decimals and why Decimal(float('1.1')) == Decimal('1.1') returns False.

As pointed in the source code, DRF will use strings unless the coder provides a float.
My opinion is, if the coder provides a float, he'll run into issues anyway, not DRF's fault.

**Comment by thenewguy** [comment] 2015-09-05 16:18
@xordoquy Maybe my post wasn't written well but I am using Decimals and they were unexpectedly serialized as float instead of string.  I wan't them to be serialized to strings in json by default but currently one must manually catch all places where Decimals are passed to a serializer directly and manually cast them to strings.

For example, if your api view returns the following:
```
return Response([Decimal("1.1")], status=status.HTTP_400_BAD_REQUEST)
```
it will render 1.1 as a json float instead of a json string:
```
[1.1]
```

**Comment by xordoquy** [comment] 2015-09-06 21:07
@thenewguy I think I got your point but I'm feeling like it's pretty different from the original issue.

**Comment by tomchristie** [comment] 2015-09-07 08:48
@thenewguy - If you pass `Decimal` instances through a `DecimalField` they will be coerced to strings by default. If you don't it's up to you to either:

1. Decide if you want to coerce them to strings or not.
2. Use a custom renderer to always coerce them to strings.

The way around we do things allows users to more easily choose between string and float representations, in most cases by just setting the `COERCE_DECIMAL_TO_STRING` setting.

**Comment by xordoquy** [comment] 2015-09-07 08:54
@tomchristie I think the issue isn't with the serialization in itself but at the deserialization stage - hence my previous comment.
What happens when the `json` module gets say `1.1` is that it'll cast it into a `float` then DRF will make it a `Decimal`. At this point we may have a slight glitch with the float representation.
I'll try to come up with an example about this this week.
