### ISSUE TITLE
HyperlinkedRelatedField 2nd degree relations generate wrong url (v3.1.1)

### ISSUE THREAD

**Issue by martinhill** [tomchristie/django-rest-framework#2826] opened 2015-04-15 22:30 UTC
A HyperlinkedRelatedField with a source argument generates the wrong url. For example,

```python
class UserSerializer(serializers.HyperlinkedModelSerializer):
    customer = serializers.HyperlinkedRelatedField(
        read_only=True,
        view_name='customer-detail',
        source='userprofile')

class CustomerSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Customer

class CustomerViewSet(viewsets.ModelViewSet):
    serializer_class = CustomerSerializer
    etc...
```

If user.userprofile.pk == 5, and userprofile.customer.pk == 7, the generated url will be `http:/.../api/customer/5/` instead of `http:/.../api/customer/7/`, having taken the pk from the intermediate model instead of the desired relation.

I'm not sure if this is by design and 2nd degree hyperlinked relation aren't supported, but couldn't find any mention in the docs. As a workaround I'm able to nest the Customer in the UserSerializer, but thought I'd mention this.

Thanks!
Martin

**Comment by xordoquy** [comment] 2015-04-15 22:39
@martinhill I'm missing a point here as the associated models are missing.
Assuming there's a FK from `User` to `UserProfile` and from `UserProfle` to `Customer` I don't see why the hyperlink should have given id pk of 7.
`UserSerializer.customer` will be using `UserSerializer.userprofile` as its source hence the user.userprofile.pk.

**Comment by martinhill** [comment] 2015-04-16 01:51
@xordoquy, sorry for the omission. They're linked by OneToOneFields like this:

```
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)

class Customer(StripeObject):
    subscriber = models.OneToOneField(UserProfile, null=True)
```

So as you said there's an FK from `User` to `UserProfile` and from `UserProfile` to `Customer`. I would have thought since the hyperlink is to a `Customer` instance, confirmed by producing a link to `/api/customer/`, that the id would correspond to the customer, not the UserProfile. It just seems inconsistent, or perhaps I'm missing something. I couldn't find an example of a `HyperlinkedRelatedField` with a `source` argument, so I'm just guessing how to achieve the desired behavior. When I tried passing `source='userprofile.customer'`, it resulted in an `AttributeError at /api/user/
'UserProfile' object has no attribute 'userprofile'`

Perhaps hyperlinking to an indirectly related model is an uncommon use-case, but it almost works, or I just haven't figured it out.

**Comment by kevin-brown** [comment] 2015-04-16 02:28
The `source` argument is supposed to tell DRF where to look to get the value for the field. By default, the `source` is the same as the field name (`customer`). So when DRF would get the field value, it would look at `obj.customer`.

By setting the source to `userprofile`, you are telling DRF to get the value for the field from `userprofile`, so DRF looks at `obj.userprofile`. This is why you are getting `7` (`obj.userprofile.pk`) instead of `5` (`obj.userprofile.customer.pk`).

Now, setting the `source` to `userprofile.customer` _should_ solve your issue, as that _should_ be the dotted path to get the `Customer` from the `User`. If this isn't the case, it'd be awesome to see a failing test case made so we can work towards a fix.

_Side note: It doesn't look like `UserSerializer` is actually being used in the view._

**Comment by martinhill** [comment] 2015-04-16 14:36
@kevin-brown good idea, I'll play around with writing a test case for this..

**Comment by tomchristie** [comment] 2015-04-16 16:31
> setting the source to userprofile.customer should solve your issue, as that should be the dotted path to get the Customer from the User. If this doesn't actually work, it'd be awesome to see a failing test case made so we can work towards a fix.

Seconding @xordoquy there.

This may sound unhelpful but right now I'd suggest closing this issue until and unless we have an absolutely minimal example or test case. As presented the issue is a little convoluted and I'd like to see it narrowed down before accepting it.

**Closed by tomchristie** 2015-04-16 16:31 UTC
