### ISSUE TITLE
Save ModelSerializer with OneToOneField which is also primary_key error

### ISSUE THREAD

**Issue by buendiya** [tomchristie/django-rest-framework#4483] opened 2016-09-12 15:31 UTC
When I try to save ModelSerializer with OneToOneField which is also primary_key, it raise an error:
ValueError: Cannot assign "1": "Garage.car" must be a "Car" instance.

## Steps to reproduce
class Car(models.Model):
    name = models.CharField(max_length=255, blank=True)

class CustomOneToOneField(models.OneToOneField):
    rel = RevealAccess(True, 'rel')

class GarageSerializer(serializers.ModelSerializer):
    class Meta:
        model = Garage
        fields = ('car', )

gs = serializers.GarageSerializer(data={'car':c.pk})
gs.is_valid()   # output True
gs.save()

## Expected behavior
Save succeed

## Actual behavior
ValueError: Cannot assign "1": "Garage.car" must be a "Car" instance.

**Comment by xordoquy** [comment] 2016-09-12 19:19
I'm going to close this as this isn't actionnable in its current state.
Will consider reopening with a failing test case.

**Closed by xordoquy** 2016-09-12 19:19 UTC

**Comment by h3l** [comment] 2017-07-10 07:22
Also meet this error. Please fix it.

**Comment by xordoquy** [comment] 2017-07-10 07:43
As I said, this isn't actionnable in its current form.
There are several part missing from the code sample that are required to make it run.
We can not afford to spent time with incomplete reports while we already have some fully described that are already waiting for us.

Note that this doesn't mean the issue is invalid, just that it needs something we can start working on.
