### ISSUE TITLE
is_valid() fails for serializer with RegexValidator

### ISSUE THREAD

**Issue by scjody** [tomchristie/django-rest-framework#4205] opened 2016-06-17 19:19 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

A failing test is added in #4204.

* Create a `ModelSerializer` with a `RegexValidator` on one of the fields.
* Create an instance of the `ModelSerializer` with data.
* Call `is_valid()` on the instance.

## Expected behavior

`is_valid()` returns `True` or `False`

## Actual behavior

Exception due to deepcopy issue:
```
Traceback (most recent call last):
  File "/var/www/streambed/drf_issue/users/tests.py", line 11, in test_create_user
    slz.is_valid()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 213, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 407, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 431, in to_internal_value
    fields = self._writable_fields
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 346, in _writable_fields
    field for field in self.fields.values()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 339, in fields
    for key, value in self.get_fields().items():
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 923, in get_fields
    extra_kwargs = self.get_extra_kwargs()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 1215, in get_extra_kwargs
    extra_kwargs = copy.deepcopy(getattr(self.Meta, 'extra_kwargs', {}))
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
```

Worked in 3.3.2; broken in 3.3.3 and on master.

May be related to #1954, but that was fixed and this problem still exists.

**Comment by kevin-brown** [comment] 2016-06-20 13:38
This appears to be related to [Python issue 10076](https://bugs.python.org/issue10076), which I have a feeling won't be fixed any time soon.

**Comment by mihaigociu** [comment] 2016-06-21 12:30
The failing test works fine for me. is_valid() returns False, as it should.

**Comment by mihaigociu** [comment] 2016-06-22 10:16
The problem is deep copying the RegexValidator.

`validator = RegexValidator('^\w+$')
copy.deepcopy(validator)`

will result in an error: `*** TypeError: cannot deepcopy this pattern object`

**Comment by mihaigociu** [comment] 2016-06-22 10:29
Using a RegexValidator with `__deepcopy__` implemented fixed it for me

`def __deepcopy__(self, memo):
        return RegexValidator(self.regex, self.message, self.code, self.inverse_match, self.flags)`

**Comment by tomchristie** [comment] 2016-06-22 10:33
Thanks for the feedback, @mihaigociu

**Comment by tomchristie** [comment] 2016-08-02 11:05
Note that this only fails on Django 1.8, but not Django 1.9 or 1.10.

Going to suggest that we close this off, and accept it as a 1.8 limitation.
I'd be happy to consider PR's that do address this, but otherwise think the easiest solution is the `__deepcopy__` implementation you mention here.

Thanks for having raised this!

**Closed by tomchristie** 2016-08-02 11:05 UTC
Labels: Needs further review
